include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_literals_to_create_immutables
    - prefer_const_declarations
    - avoid_unnecessary_containers

    - always_declare_return_types
    - avoid_init_to_null
    - avoid_unused_constructor_parameters
    - avoid_returning_null
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_interpolation_to_compose_strings
    - prefer_typing_uninitialized_variables

    - unnecessary_null_checks
    - unnecessary_this
    - use_super_parameters
    - avoid_renaming_method_parameters
    - avoid_redundant_argument_values
